### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [elifoster/ModShields#1]
- [ ] Home page similar to shields.io.
- [x] FTB Gamepedia completion
  - Check the provided article if it exists, and how many redlinks it contains.
- [x] CurseForge latest version
  - Check the CurseForge project ID latest version name. Everything after the second -
- [x] CurseForge total downloads
  - Check the CurseForge project ID total downloads. Probably need to do some HTML parsing for this.
- [ ] CurseForge monthly downloads
  - Check the Curse (not CF) project ID monthly downloads. Probably need to do some HTML parsing for this.
